### ISSUE TITLE
Tool package ID is a little odd

### ISSUE THREAD

**Issue by anurse** [Microsoft/Atlas#84]
Why is the tool package named `dotnet-atlas` when the tool is called `atlas` and doesn't actually execute as part of the `dotnet` CLI? As far as I can tell, `atlas` isn't limited to .NET projects and just happens to be written in .NET (awesome!). It's probably a good idea to use a name like `atlas-cli` if possible (and better to change this now than after a 1.0 ships ;))

**Comment by lodejard** [comment]
Yeah, it's true the nupkg names are a bit all over the place. There are a few reasons it ended up with those names, but they're not necessarily good reasons. The first way to install earlier on was with a Chocolatey package, which was named `atlas-cli`, and you can see where that's still in place:

https://github.com/Microsoft/Atlas/blob/7d35662e05c8d12fa91422e78ddadfb2813f03eb/src/Microsoft.Atlas.CommandLine.Chocolatey/Microsoft.Atlas.CommandLine.Chocolatey.csproj#L5

Then when a tool package was created it wasn't clear if it would be better to run as `atlas ...` or `dotnet atlas ...` command. Because the `atlas` nupkg name is already occupied, a `dotnet-atlas` nupkg was added. Then turned out to seem better to run as `atlas ...`, which is why the package and command name don't match.

So all that said `dotnet tool install -g` has been working beautifully... Sounds like you'd recommend removing the `atlas-cli` Chocolatey package, and rename the global tool package from `dotnet-atlas`  to `atlas-cli`?

**Comment by anurse** [comment]
> Then when a tool package was created it wasn't clear if it would be better to run as `atlas ...` or `dotnet atlas ...` command.

Yeah, that makes sense. Prior to global tools, all commands had to be run under `dotnet` so the naming made a little more sense. We've been trying to keep the `dotnet-` prefix "reserved" for commands that are actually designed for *extending* the .NET CLI. It's definitely *good* that even though the package ID is `dotnet-atlas`, the command name is `atlas`. I'd just suggest that the package ID also drop `dotnet-` to avoid confusion.

Chocolatey is a separate gallery (if I remember correctly) so I don't think there's a technical reason you couldn't use the same name in both.
